controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    panda_left_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    panda_right_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


panda_left_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - panda_left_joint1
      - panda_left_joint2
      - panda_left_joint3
      - panda_left_joint4
      - panda_left_joint5
      - panda_left_joint6
      - panda_left_joint7


panda_right_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - panda_right_joint1
      - panda_right_joint2
      - panda_right_joint3
      - panda_right_joint4
      - panda_right_joint5
      - panda_right_joint6
      - panda_right_joint7